name: build
on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: jamjarlabs/jamjar-build-image:v0.1.0
    steps:
    - name: Check out code into the CI directory
      uses: actions/checkout@v2

    - name: Lint, beautify, and test
      env:
        CC: gcc # Using gcc/g++ for now due to this issue: https://bugs.launchpad.net/ubuntu/+source/libsdl2-ttf/+bug/1872023
        CXX: g++
      run: |
        # Set up build
        cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON . -B build
        cd build

        # Линтер проверит код, выведет отчет в лог, но не уронит сборку
        make lint || true
        make beautify
        git diff --exit-code

        # Build unit tests
        make JamJarTests

    - name: Build WebAssembly (Duel Game)
      env:
        CC: emcc
        CXX: em++
      run: |
        emcmake cmake -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -DJAMJAR_NATIVE_COMPILE_UNIT_TESTS=OFF . -B build
        cd build

        make Duel

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: math-duel-web-release
        path: |
          index.html
          Duel.js
          Duel.wasm
